### PR TITLE
RFC for TA Key Provisioning

### PR DESCRIPTION
**Pull request by mhabrat**

### CODE REVIEW

**Comment by Hanlin928** [comment]
Last parameter `*parameters` of sa_ta_key_provision() is not used for these three key types, "WIDEVINE_OEM_PROVISIONING",
"PLAYREADY_MODEL_PROVISIONING", "NETFLIX_PROVISIONING", right?

**Comment by Hanlin928** [comment]
According to the current description, the data structure of WidevineProvisioning is defined in the Provisioning 3.0 model format. MTK currently only supports the provisioning 2.0 model, we cannot transform to provisioning 2.0 model format from the data structure of WidevineProvisioning. We would like to confirm with you which version of Widevine is expected to be used (v16,v17,v18), as well as which Provisioning model will be utilized (2.0, 3.0, 4.0) .

**Comment by hchoi-brcm** [comment]
in_length is supposed to be the size of structure, 'struct xxxProvisioning', right? What do we expect 'parameters'?
How about Widevine provisioning with KeyBox?
I assume the key material of each provisioning structure is wrapped (encrypted), is my understanding correct?

**Comment by jackliavg** [comment]
"5.	The key will be loaded for use within the TA. If the key received by the TA is new or updated
    and the TA supports secure storage, it will store the key to TA Secure Storage."
How does TA know the received key is new or update?

**Comment by Hanlin928** [comment]
Based on our understanding, the Netflix key is a combination of ESNID and KpeKph data. The KpeKph data should be passed to Netflix TA for installation (saving it to secure storage). In this proposed structure, which one represents the KpeKph data?

**Comment by mhabrat** [comment]
> Last parameter `*parameters` of sa_ta_key_provision() is not used for these three key types, "WIDEVINE_OEM_PROVISIONING", "PLAYREADY_MODEL_PROVISIONING", "NETFLIX_PROVISIONING", right?
The `parameters` argument is used to specify the key that will be used to unwrap the keys from the provisioning service, similar in usage in sa_key_import(). For now, this would be  SA_KEY_FORMAT_SOC but could be expanded/different in the future.

**Comment by mhabrat** [comment]
> According to the current description, the data structure of WidevineProvisioning is defined in the Provisioning 3.0 model format. MTK currently only supports the provisioning 2.0 model, we cannot transform to provisioning 2.0 model format from the data structure of WidevineProvisioning. We would like to confirm with you which version of Widevine is expected to be used (v16,v17,v18), as well as which Provisioning model will be utilized (2.0, 3.0, 4.0) .
As of now, the existing provisioning service only supports the Provisioning 3.0 model. There may be support added for the Provisioning 4.0 model in the near future. Provisioning 2.0 is not supported. Widevine version is outside the scope of this source code repository.

**Comment by mhabrat** [comment]
> in_length is supposed to be the size of structure, 'struct xxxProvisioning', right? What do we expect 'parameters'? How about Widevine provisioning with KeyBox? I assume the key material of each provisioning structure is wrapped (encrypted), is my understanding correct?

The `parameters` argument is used to specify the key that will be used to unwrap the keys passed in the "in" buffer from the provisioning service, similar in usage in sa_key_import(). For now, this would be  SA_KEY_FORMAT_SOC but could be expanded/different in the future. The existing provisioning service does not support KeyBox provisioning. in_length is the size of the in data which will depend on the buffer structure.

**Comment by mhabrat** [comment]
> "5. The key will be loaded for use within the TA. If the key received by the TA is new or updated and the TA supports secure storage, it will store the key to TA Secure Storage." How does TA know the received key is new or update?

The TA will need to compare what was received against what it currently has to determe if it is either the same key or a new key.

**Comment by jackliavg** [comment]
> > "5. The key will be loaded for use within the TA. If the key received by the TA is new or updated and the TA supports secure storage, it will store the key to TA Secure Storage." How does TA know the received key is new or update?
> 
> The TA will need to compare what was received against what it currently has to determe if it is either the same key or a new key.

In case of reprovision/prefetch, there could be several layers(directories) of DRM data, and TA may not know which layer to compare to.

**Comment by Hanlin928** [comment]
> > According to the current description, the data structure of WidevineProvisioning is defined in the Provisioning 3.0 model format. MTK currently only supports the provisioning 2.0 model, we cannot transform to provisioning 2.0 model format from the data structure of WidevineProvisioning. We would like to confirm with you which version of Widevine is expected to be used (v16,v17,v18), as well as which Provisioning model will be utilized (2.0, 3.0, 4.0) .
> > As of now, the existing provisioning service only supports the Provisioning 3.0 model. There may be support added for the Provisioning 4.0 model in the near future. Provisioning 2.0 is not supported. Widevine version is outside the scope of this source code repository.

We have plan to support Provisioning 4.0 model, when will SecAPI supports Provisioning 4.0 model?

**Review by riwoh — APPROVED** [review]

**Review by JRHewitt-CC — APPROVED** [review]

**Pull request merged**
