### PR TITLE
Add sa_key_provision_ta function

### PR DESCRIPTION
**Pull request by seanjin99**
Add sa_key_provision_ta function and unit tests

### CODE REVIEW

**Comment by mhughesacn** [comment]
Please explain what the two binary files are.  Are they in any way confidential?
Martin
RDK CMF Compliance Team

**Comment by seanjin99** [comment]
> Please explain what the two binary files are. Are they in any way confidential? Martin RDK CMF Compliance Team

these two files are used to provide an example how to read encrypted key and  certification from storage.
#1. 0351000003510001.key is I use RSA algorithm  created with random bytes. 
#2. 0651000006510001.bin is a certification data which is retrieved from key server and it is encrypted.

**Comment by mhughesacn** [comment]
> > Please explain what the two binary files are. Are they in any way confidential? Martin RDK CMF Compliance Team
> 
> these two files are used to provide an example how to read encrypted key and certification from storage. #1. 0351000003510001.key is I use RSA algorithm created with random bytes. #2. 0651000006510001.bin is a certification data which is retrieved from key server and it is encrypted.

Thanks Sean: And the second part of my question, to be clear: there is therefore nothing confidential about this pair of files?

**Comment by seanjin99** [comment]
> > > Please explain what the two binary files are. Are they in any way confidential? Martin RDK CMF Compliance Team
> > 
> > 
> > these two files are used to provide an example how to read encrypted key and certification from storage. #1. 0351000003510001.key is I use RSA algorithm created with random bytes. #2. 0651000006510001.bin is a certification data which is retrieved from key server and it is encrypted.
> 
> Thanks Sean: And the second part of my question, to be clear: there is therefore nothing confidential about this pair of files?

yes. the certificate file is X.509 certificate format, contains a public key and signed.

**Pull request closed without merging**
